development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d8mt4i8vtv31eg
  pool: 5
  timeout: 5000
  user: kflfoavnkchuwo