# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6554087fecde67fd93caeebc2f47a79d25b80107fa8abca8262742a83d72f4b7872b0c2ad76871420b251a8dda9a44f8a6aab89192d2466efba290d9ab2d4d0d

test:
  secret_key_base: 92eb74d7c4c02374a7f3e785e7eea727ec65b6b70e3cc2e34f4250454e2e2dc635a803137de53c932e931a825d0cbb5c0d90e407aa8170e80ad36fc54bc36971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
